import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
 title: "PurpleCat GPT App",
 description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <>
   <head>
    <link
     rel='icon'
     href='data:image/svg+xml,
    <svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22>
    <text y=%22.9em%22 font-size=%2290%22>🎆</text></svg>'></link>
   </head>

   <ClerkProvider>
    <html lang='en'>
     <body className={inter.className}>
      <Providers>{children}</Providers>
     </body>
    </html>
   </ClerkProvider>
  </>
 );
}
